import type { CSSProperties } from "react";

export const s = {
  anchor: { position: "relative", display: "inline-flex" } satisfies CSSProperties,
  card: (above: boolean): CSSProperties => ({
    position: "absolute",
    left: 0,
    ...(above ? { bottom: "calc(100% + 8px)" } : { top: "calc(100% + 8px)" }),
    zIndex: 40,
    width: 480,
    maxWidth: "min(480px, 90vw)",
    padding: 12,
    borderRadius: 10,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    boxShadow: "0 12px 32px rgba(0,0,0,0.35)",
    display: "flex",
    flexDirection: "column",
    gap: 10,
    textAlign: "left",
    cursor: "default",
    fontWeight: 400,
  }),
  header: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  muted: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  row: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    paddingTop: 8,
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  titleRow: { display: "flex", alignItems: "center", gap: 8, minWidth: 0 } satisfies CSSProperties,
  sevIcon: (color: string, bg: string): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 20,
    height: 20,
    borderRadius: 5,
    color,
    background: bg,
    flexShrink: 0,
  }),
  prefix: { fontSize: 11, color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  title: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  category: { fontSize: 11, color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  locRow: { display: "flex", alignItems: "center", gap: 10, fontSize: 11.5 } satisfies CSSProperties,
  loc: { color: "var(--accent)" } satisfies CSSProperties,
  conf: { color: "var(--text-muted)" } satisfies CSSProperties,
  rationale: {
    fontSize: 12,
    color: "var(--text-secondary)",
    lineHeight: 1.45,
  } satisfies CSSProperties,
  more: { fontSize: 11.5, color: "var(--text-muted)", paddingTop: 6 } satisfies CSSProperties,
};
